quarkus.http.enabled=false
quarkus.lambda.handler=feedback

quarkus.log.console.json=true
quarkus.log.level=INFO

feedback.dynamodb.table-name=${FEEDBACK_DYNAMODB_TABLE_NAME:Feedbacks}
feedback.sqs.queue-url=${FEEDBACK_SUBMITTED_QUEUE_URL:}
