# Configurações Gerais
quarkus.http.enabled=false
quarkus.log.console.json=true
quarkus.log.level=INFO

# Variáveis de Ambiente
feedback.dynamodb.table-name=${FEEDBACK_DYNAMODB_TABLE_NAME:Feedbacks}
feedback.sqs.queue-url=${FEEDBACK_SUBMITTED_QUEUE_URL:}

# --- OTIMIZAÇÃO DE COLD START (AWS SDK) ---

# Força o uso do cliente URL Connection (Sincrono e Leve)
quarkus.dynamodb.sync-client.type=url
quarkus.sqs.sync-client.type=url

# Desabilita a busca automática de região e credenciais (usa as do ambiente Lambda)
# Isso evita chamadas de rede desnecessárias no boot
quarkus.dynamodb.aws.region.provider.type=system-property
quarkus.dynamodb.aws.credentials.type=default

quarkus.sqs.aws.region.provider.type=system-property
quarkus.sqs.aws.credentials.type=default

# Otimização Nativa (Ajuda na serialização JSON)
quarkus.native.additional-build-args=-H:+AllowFoldMethods