feedback.dynamodb.table-name=Feedbacks

auth.enabled=false
email.admin.address=gustavo.jog+admin@hotmail.com
email.source.address=gustavo.jog+noreply@hotmail.com

quarkus.lambda.handler=notificationProcessor

quarkus.log.console.json=true
quarkus.log.level=INFO
